### ISSUE TITLE
ORLANDO: Date entity: Date picker values and schema required values clash

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#318]
see the validation error message vs the description in the 
![image](https://cloud.githubusercontent.com/assets/6600070/7358528/23dbc650-ecf3-11e4-9bf5-58fd7d6169ea.png)

We agreed internally to use slightly modified Orlando schemas with CWRC Writer (for the time being). @brundin will provide the new schema urls to @ajmacdonald  to reference from within CWRC Writer

**Comment by brundin** [comment]
* MRB: Mon 04-May-2015: *_v2 schema copies of the Orlando biography, event, and writing schemas use the ISO 8601 date format rather than the customized Orlando date format; this meant making changes to the defined pattern in the VALUE attribute in the DATE element, the FROM and TO attributes in the DATERANGE element, and the VALUE attribute in the DATESTRUCT element.
