### ISSUE TITLE
Revise Selection Panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#328]
Consider also making this a button on the banner or menu as people will want to do this a lot.

**Comment by ilovan** [comment]
Hi @ajmacdonald , how difficult do you foresee the two components of this issue to be?

Would it be possible to instate at least the settings panel option this week?

**Comment by ajmacdonald** [comment]
Adding a new button is trivial. However, the ability to show attributes alongside the tags in the manner that it currently functions is very difficult / impossible.
A possible middle ground is perhaps making the Selection panel more prominent, as it displays all tags and attributes and text content of the current selection.

**Comment by SusanBrown** [comment]
Just to confirm what you seem to be saying:

it would be really difficult or impossible to have what currently reads:
TITLE in angle brackets, embedded in the view of the text
read
TITLE TYPE=“ANALYTIC” in angle brackets, optionally (toggled on or off via the settings just like SHOW TAGS is now) embedded in the view of the text?

**Comment by ajmacdonald** [comment]
Correct.

**Comment by SusanBrown** [comment]
Yeeesh. Hard to believe and really regrettable, as this would really improve the functionality. 

Perhaps you could elaborate more on the alternative you suggested for enhancing how the panel works. Right now I think you have to dig quite a ways to get to the attribute (i.e. several clicks).

**Comment by ajmacdonald** [comment]
Thinking more about this...
The current way that the tags are displayed is through using CSS rules. This is doable for tags since they're generic. In order to display attribute info that's specific to each particular tag, I'd need to generate specific rules for each tag instance (as opposed to the tag in general) and alter them each time the tag is altered, then reload the entire CSS file. I can try this out and see how much it affects browser performance.

**Comment by susanirenebrown** [comment]
Sounds very time-consuming.

Unless it proves to be super fast and easy to do, perhaps in the long run we should do this in a way that would let users who are uploading a new schema do the work that enables this. I expect that putting that in place would be quite involved, and so it would be for later if users really want this. I think they will, though, unless we can come up with a way of displaying it in the markup panel more obviously, which is what I think you were initially suggesting.

**Comment by ajmacdonald** [comment]
Super fast and easy? I don't think it would be.

I don't see how changes to a schema would facilitate this functionality in the editor.

We could maybe change the layout so that the Selection panel (which displays the markup of the selected text) is always visible.
![markup](https://cloud.githubusercontent.com/assets/882444/11281691/a7f53480-8ec9-11e5-80bd-19b597114ed1.png)

**Comment by SusanBrown** [comment]
The strategy of showing what is in the selection panel, or making that an option, is hopeful, since that is exactly what people would want to see. Would it be possible by any chance to have what’s in the selected tag (or the lowest in the hierarchy, as seems to be the case here) display in the crumb trail?

**Comment by ajmacdonald** [comment]
So, just to be clear, this selection panel already exists. However, it's fairly hidden in the interface.

How would you envision the content of the selected tag being in the crumb trail?

**Comment by SusanBrown** [comment]
So where a crumbtrail currently might say:
TEI>>text>>body>>div>>p>>placeName
it would instead say
TEI>>text>>body>>div>>p>>date 
when=1935-10-21 cert=Definite

However, I think that the selection panel, since it already exists, has more promise. Right now, if I am correct, it opens only if you click on validate, then select the Selection panel, and then select some text. 

Could we perhaps do this instead: instead of having the View Source button open up a popup window, let's have it open up the selection panel instead, and have it load the entire doc if nothing is selected, and refine to just showing the selection if a selection is made in the document.  Perhaps mirror the style of buttons at the top of the Validation screen to give the option of "All" "Selection" although I'm honestly not sure that would be necessary as I think that people would figure it out pretty fast.

Let's rename the hover label for the panel View Markup

**Comment by SusanBrown** [comment]
@jchartrand I'd appreciate your reviewing and weighing in on this since it's a pretty major change I'm suggesting.

**Comment by jchartrand** [comment]
Wanting to easily view the underlying source for a specific bit of text makes total sense to me.  I favour your suggestion to spawn the selection panel from a View Markup button, rather than show attributes in a crumb trail.  

How hard would it be, Andrew, to spawn the selection panel from a View Markup button, showing the markup for any currently selected text, or the whole document if no text was selected when the button was pushed?

Maybe we could also include a big question mark on the selection panel title that spawns a dismissible popup explaining what the selection panel does, and that you can select specific chunks of text to see just that markup?

**Comment by ajmacdonald** [comment]
"How hard would it be, Andrew, to spawn the selection panel from a View Markup button, showing the markup for any currently selected text, or the whole document if no text was selected when the button was pushed?"

It would be fairly trivial.

**Comment by SusanBrown** [comment]
Fabulous!

On Aug 3, 2016, at 3:02 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


"How hard would it be, Andrew, to spawn the selection panel from a View Markup button, showing the markup for any currently selected text, or the whole document if no text was selected when the button was pushed?"

It would be fairly trivial.

**Comment by ajmacdonald** [comment]
Please test.

**Comment by SusanBrown** [comment]
Done!
